custom_fastfetch_metrics:
  - type: command
    key: "Internal IPv4"
    text: "ip a s eth1 | grep -o 'inet [0-9.]\\+' | awk '{printf \"%s \", $2}'"
    keyColor: "red"
    valueColor: "default"

  - type: command
    key: "FQDN"
    text: "nslookup $(hostname -I | awk '{print $1}') | awk -F'= ' '/name/ {print $2}' | cut -d' ' -f1 | sed 's/\\.$//'"
    keyColor: "red"
    valueColor: "default"

  - type: command
    key: "BGP Local AS"
    text: "birdc s p all | grep 'Local AS' | awk '{print $3}' | uniq"
    keyColor: "red"
    valueColor: "default"

  - type: command
    key: "BGP Router ID"
    text: "birdc s status | grep 'Router ID' | awk '{print $4}'"
    keyColor: "red"
    valueColor: "default"

  - type: command
    key: "BGP Sessions"
    text: "birdc s p | grep Established | wc -l"
    keyColor: "red"
    valueColor: "default"
