hcloud_server_type: cpx32
hcloud_location: nbg1
hcloud_image: debian-12
hcloud_ssh_keys:
  - jzielke_hetzner
hcloud_enable_ipv4: true
hcloud_enable_ipv6: true
hcloud_private_networks:
  - name: net_ffkbu
    ip: 10.0.1.3

hcloud_dns_ptr: sv01.kbu.freifunk.net
